# Generated by Django 6.0.5 on 2026-06-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Укажите дату и время начала отправки писем.", verbose_name="Начало рассылки"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Укажите дату и время завершения отправки писем.", verbose_name="Окончание рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        max_length=9,
                        verbose_name="Статус рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status", "message"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300, verbose_name="Тема сообщения")),
                ("content", models.TextField(verbose_name="Содержание письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Электронная почта получателя")),
                ("first_name", models.CharField(blank=True, max_length=50, null=True, verbose_name="Имя получателя")),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Отчество получателя"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Фамилия получателя"),
                ),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "send_time",
                    models.DateTimeField(
                        help_text="Дата и время попытки отправки ", verbose_name="Дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("success", "Успешно"), ("fail", "Не успешно")],
                        default=None,
                        max_length=7,
                        null=True,
                        verbose_name="Статус отправки",
                    ),
                ),
                ("server_response", models.TextField(verbose_name="Ответ сервера-получателя")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="distribution.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["mailing", "recipient"],
            },
        ),
    ]
