# Generated by Django 6.0.5 on 2026-06-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distribution", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                help_text="Укажите дату и время завершения отправки писем.", verbose_name="Окончание рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Выберите получателей рассылки",
                related_name="mailings",
                to="distribution.recipient",
                verbose_name="Получатели",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                help_text="Укажите дату и время начала отправки писем.", verbose_name="Начало рассылки"
            ),
        ),
    ]
